# Generated by Django 6.0 on 2025-12-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='rut',
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
    ]
