# Generated by Django 6.0 on 2025-12-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_remove_paciente_fecha_nacimiento_remove_paciente_rut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
