# Generated by Django 6.0 on 2025-12-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_remove_paciente_telefono_paciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
    ]
