# Generated by Django 6.0 on 2025-12-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_paciente_edad_alter_paciente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
